services:
  db:
    image: postgres:15-alpine
    container_name: st_finance_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ST_Finance
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    image: st_finance_api:latest
    container_name: st_finance_api
    build:
      context: .
      dockerfile: ST_finance.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DbConnection=Host=db;Port=5432;Database=ST_Finance;Username=postgres;Password=postgres;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

volumes:
  pgdata:
